[tool.black]
line-length = 120
target-version = ["py38"]

[tool.isort]
profile = "black"
line_length = 120
py_version = "38"
atomic = true
src_paths = ["src"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --strict-markers"
testpaths = ["tests"]
filterwarnings = ["once::Warning"]
